### ISSUE TITLE
Support for Firefox

### ISSUE THREAD

**Issue by filips123** [zlikavac32/codepf-chrome-extension#6]
Please add support for Firefox. This should not be hard as Firefox also supports WebExtensions API.

**Comment by zlikavac32** [comment]
@filips123 Thank you for the interest in this extension. I will give it a shot, although I can't give any deadline, since I'm not a JS dev and I'll have to explore it first :)

**Comment by filips123** [comment]
@zlikavac32 [Here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension) are some details how to do that.

**Comment by zlikavac32** [comment]
@filips123 Looks easy enough, I sure hope it will be :D. Thank you for the link

**Comment by zlikavac32** [comment]
@filips123 It's available on https://addons.mozilla.org/en-US/firefox/addon/code-path-finder/

**Comment by filips123** [comment]
@zlikavac32 Can you also link it from README?

**Comment by zlikavac32** [comment]
@filips123 I will, but first I plan to add one new feature to it and then update readme :)
